//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileLogs
    {
        public FileLogs()
        {
            this.Sales = new HashSet<Sales>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string FileName { get; set; }
        public int Manager_Id { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
    
        public virtual ICollection<Sales> Sales { get; set; }
        public virtual Managers Managers { get; set; }
    }
}
