//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Sum { get; set; }
        public int Article_Id { get; set; }
        public int Client_Id { get; set; }
        public int FileLog_Id { get; set; }
        public System.DateTime AddTime { get; set; }
    
        public virtual Articles Articles { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual FileLogs FileLogs { get; set; }
    }
}
